apiVersion: apps/v1
kind: Deployment
metadata:
  name: like-service
  labels:
    app: like-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: like-service
  template:
    metadata:
      labels:
        app: like-service
    spec:
      containers:
      - name: like-service
        image: morrishh/babbly-like-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: CassandraHosts
          valueFrom:
            secretKeyRef:
              name: cassandra-secrets
              key: CASSANDRA_HOSTS
        - name: CassandraKeyspace
          value: "babbly_likes"
        - name: CassandraUsername
          valueFrom:
            secretKeyRef:
              name: cassandra-secrets
              key: CASSANDRA_USERNAME
        - name: CassandraPassword
          valueFrom:
            secretKeyRef:
              name: cassandra-secrets
              key: CASSANDRA_PASSWORD
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_LIKE_TOPIC
          value: "like-events"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 20
      # imagePullSecrets:
      # - name: acr-secret # If your ACR requires authentication from K8s cluster 