apiVersion: apps/v1
kind: Deployment
metadata:
  name: babbly-like-service
  labels:
    app: babbly-like-service
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: babbly-like-service
  template:
    metadata:
      labels:
        app: babbly-like-service
    spec:
      containers:
      - name: babbly-like-service
        image: babbly-like-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # Assuming your app listens on port 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: CassandraHosts
          valueFrom:
            secretKeyRef:
              name: cassandra-secrets # Name of your K8s secret for Cassandra
              key: CASSANDRA_HOSTS
        - name: CassandraKeyspace
          value: "babbly_likes"
        - name: CassandraUsername
          valueFrom:
            secretKeyRef:
              name: cassandra-secrets
              key: CASSANDRA_USERNAME
        - name: CassandraPassword
          valueFrom:
            secretKeyRef:
              name: cassandra-secrets
              key: CASSANDRA_PASSWORD
        # Add other environment variables as needed
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        # readinessProbe and livenessProbe are highly recommended for production
        readinessProbe:
          httpGet:
            path: /health # Assuming you have a /health endpoint
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health # Assuming you have a /health endpoint
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
      # imagePullSecrets:
      # - name: acr-secret # If your ACR requires authentication from K8s cluster 