apiVersion: v1
kind: Service
metadata:
  name: like-service
  labels:
    app: like-service
spec:
  type: ClusterIP
  selector:
    app: like-service
  ports:
  - name: http
    protocol: TCP
    port: 8083
    targetPort: 8083 