apiVersion: v1
kind: Service
metadata:
  name: babbly-like-service
  labels:
    app: babbly-like-service
spec:
  type: ClusterIP
  selector:
    app: babbly-like-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http-alt 